batch_size: 1
epoch: 200
learning_rate: 1e-3
gpu: 1
num_point: 10000
optimizer: Adam
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20
model:
  nblocks: 4
  transformer_dim: 640
  group_size: 16

defaults:
  - model: Menghao

hydra:
  run:
    dir: log/normal/${model.name}

  sweep:
    dir: log/normal
    subdir: ${model.name}
