batch_size: 64
epoch: 200
learning_rate: 1.2e-3
gpu: 1
num_point: 2048
optimizer: SGD
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20
model:
  nblocks: 4
  transformer_dim: 640

defaults:
  - model: Menghao

hydra:
  run:
    dir: log/normal/${model.name}

  sweep:
    dir: log/normal
    subdir: ${model.name}
